language: en
pipeline: 
  #Default supervised_embelding
  - name: "WhitespaceTokenizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "CountVectorsFeaturizer"
  - name: "EmbeddingIntentClassifier"
  
  #Duckling
  - name: DucklingHTTPExtractor
    url: http://localhost:8000
    locale: en_GB
    timezone: Europe/Stockholm
    dimensions:    
      - minDate
      - maxDate

policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
- name: FallbackPolicy
  nlu_threshold: 0.4
  core_threshold: 0.3
  fallback_action_name: action_default_fallback
- name: FormPolicy
